//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.18 at 01:33:47 PM MSK 
//


package com.example.papers;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.example.com/papers}paper" maxOccurs="unbounded" minOccurs="2"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "paper"
})
@XmlRootElement(name = "Papers")
public class Papers {

    @XmlElementRef(name = "paper", namespace = "http://www.example.com/papers", type = JAXBElement.class)
    protected List<JAXBElement<? extends Paper>> paper;

    /**
     * Gets the value of the paper property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the paper property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPaper().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link Booklet }{@code >}
     * {@link JAXBElement }{@code <}{@link Magazine }{@code >}
     * {@link JAXBElement }{@code <}{@link Newspaper }{@code >}
     * {@link JAXBElement }{@code <}{@link Paper }{@code >}
     * 
     * 
     */
    public List<JAXBElement<? extends Paper>> getPaper() {
        if (paper == null) {
            paper = new ArrayList<JAXBElement<? extends Paper>>();
        }
        return this.paper;
    }

}
