//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.18 at 01:33:47 PM MSK 
//


package com.example.papers;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Paper complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Paper">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="isGlossy" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="isColor" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="pageCount">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;minInclusive value="1"/>
 *               &lt;maxInclusive value="10000"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="title" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="periodicity" default="uncertain">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="daily"/>
 *             &lt;enumeration value="weekly"/>
 *             &lt;enumeration value="monthly"/>
 *             &lt;enumeration value="uncertain"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Paper", propOrder = {
    "isGlossy",
    "isColor",
    "pageCount"
})
@XmlSeeAlso({
    Newspaper.class,
    Booklet.class,
    Magazine.class
})
public class Paper {

    protected boolean isGlossy;
    protected boolean isColor;
    protected int pageCount;
    @XmlAttribute(name = "title", required = true)
    protected String title;
    @XmlAttribute(name = "periodicity")
    protected String periodicity;

    /**
     * Gets the value of the isGlossy property.
     * 
     */
    public boolean isIsGlossy() {
        return isGlossy;
    }

    /**
     * Sets the value of the isGlossy property.
     * 
     */
    public void setIsGlossy(boolean value) {
        this.isGlossy = value;
    }

    /**
     * Gets the value of the isColor property.
     * 
     */
    public boolean isIsColor() {
        return isColor;
    }

    /**
     * Sets the value of the isColor property.
     * 
     */
    public void setIsColor(boolean value) {
        this.isColor = value;
    }

    /**
     * Gets the value of the pageCount property.
     * 
     */
    public int getPageCount() {
        return pageCount;
    }

    /**
     * Sets the value of the pageCount property.
     * 
     */
    public void setPageCount(int value) {
        this.pageCount = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the periodicity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPeriodicity() {
        if (periodicity == null) {
            return "uncertain";
        } else {
            return periodicity;
        }
    }

    /**
     * Sets the value of the periodicity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPeriodicity(String value) {
        this.periodicity = value;
    }

}
